### ISSUE TITLE
Getting an SSL Error. Please help

### ISSUE THREAD

**Issue by allandel73** [ibm-messaging/event-streams-samples#22]
Hi, 

I'm getting this error. Can somebody help me please?

[2/16/18 12:20:49:702 EST] 00000039 SystemOut                                                    O 12:20:49.701 [kafka-producer-network-thread | cpqi-messagehub] DEBUG o.a.k.c.network.SslTransportLayer - SSLEngine.closeInBound() raised an exception.
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:1561) ~[na:1.8.0_151]
	at org.apache.kafka.common.network.SslTransportLayer.handshakeFailure(SslTransportLayer.java:797) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:257) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:79) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:460) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:398) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
[2/16/18 12:20:49:703 EST] 00000039 SystemOut                                                    O 12:20:49.703 [kafka-producer-network-thread | cpqi-messagehub] DEBUG o.a.kafka.common.network.Selector - [Producer clientId=cpqi-messagehub] Connection with kafka02-prod02.messagehub.services.eu-gb.bluemix.net/159.8.179.150 disconnected due to authentication exception
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1214) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1186) ~[na:1.8.0_151]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469) ~[na:1.8.0_151]
	at org.apache.kafka.common.network.SslTransportLayer.handshakeWrap(SslTransportLayer.java:435) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:301) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:255) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:79) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:460) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:398) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:239) [kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) [kafka-clients-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_151]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_151]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_151]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_151]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514) ~[na:1.8.0_151]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_151]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[na:1.8.0_151]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:966) ~[na:1.8.0_151]
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:963) ~[na:1.8.0_151]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_151]
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416) ~[na:1.8.0_151]
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:389) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:469) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:328) ~[kafka-clients-1.0.0.jar:na]
	... 8 common frames omitted

**Comment by mimaison** [comment]
As this is over 6 months old and does not appear to be coming from the Java sample (because of the client-id), I'm closing this issue.

If it's still an issue, please reopen with more details.
