### ISSUE TITLE
Error: Cannot create 1 partition(s) for topic kafka-nodejs-console-sample-topic

### ISSUE THREAD

**Issue by jpeckham** [ibm-messaging/event-streams-samples#56]
C:\projects\event-streams-samples\kafka-nodejs-console-sample>docker run -e VCAP_SERVICES="%VCAP_SERVICES%" nodejs-console-sample
Using VCAP_SERVICES to find credentials.
Kafka Endpoints: broker-5-1bbc2mfrltrtt1b7.kafka.svc02.us-south.eventstreams.cloud.ibm.com:9093,broker-4-1bbc2mfrltrtt1b7.kafka.svc02.us-south.eventstreams.cloud.ibm.com:9093,broker-1-1bbc2mfrltrtt1b7.kafka.svc02.us-south.eventstreams.cloud.ibm.com:9093,broker-0-1bbc2mfrltrtt1b7.kafka.svc02.us-south.eventstreams.cloud.ibm.com:9093,broker-2-1bbc2mfrltrtt1b7.kafka.svc02.us-south.eventstreams.cloud.ibm.com:9093,broker-3-1bbc2mfrltrtt1b7.kafka.svc02.us-south.eventstreams.cloud.ibm.com:9093
Creating the topic kafka-nodejs-console-sample-topic with AdminClient
AdminClient connected
{ Error: Cannot create 1 partition(s) for topic kafka-nodejs-console-sample-topic.
The maximum number of partitions allowed (1) would be exceeded as the current count is 1
    at Function.createLibrdkafkaError [as create] (/usr/src/app/node_modules/node-rdkafka/lib/error.js:334:10)
    at /usr/src/app/node_modules/node-rdkafka/lib/admin.js:132:28
  message: 'Cannot create 1 partition(s) for topic kafka-nodejs-console-sample-topic.\nThe maximum number of partitions allowed (1) would be exceeded as the current count is 1',
  code: 44,
  errno: 44,
  origin: 'local' }

**Comment by jpeckham** [comment]
nevermind i had a topic already and the lite version only allows 1 total partition
